name: Woman. Legend. Blog.
description: American cynicism. Russian fatalism. Nutella. 
meta_description: "My blog. "

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /wlb
domain_name: 'http://veekaybee.github.com'
google_analytics: 'UA-74036868-1'
gems: [jekyll-paginate]
site-url: /
comments: true

# Details for the RSS feed generator
url:            'Woman.Legend.Blog'
author:         'Vicki'
